discussion/urls.py
from django.urls import path

from discussion import views

urlpatterns = [
    path('', views.DisplayThemesView.as_view(), name='main_page'),
    path('discussion/create/', views.CreateThemeView.as_view(), name='create_theme'),
    path('discussion/description/<int:id>/', views.DescriptionThemeView.as_view(), name='description_theme'),
    path('discussion/<str:room_id>/', views.DiscussionRoomView.as_view(), name='discussion'),
    path('discussion/<str:theme_id>/create_room/', views.CreateDiscussionRoomView.as_view(), name='create_room'),

]

portfolio_cgi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('discussion.urls')),
    path('moderator/', include('moderator.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url

from users import views

urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('', include ('django.contrib.auth.urls')),
]

discussion/models.py
from itertools import chain

from django.db import models
from django.conf import settings

from accounts.models import User


class Theme(models.Model):
    theme = models.CharField(max_length=255, verbose_name='theme')
    problem = models.TextField(verbose_name='problem')
    decision = models.TextField(verbose_name='decision')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='created date')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='author', related_name='themes')

    class Meta:
        ordering = ['-created_date', ]
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'

    def __str__(self):
        return self.theme


class Bot(models.Model):
    name = models.CharField(max_length=255, verbose_name='name')
    avatar = models.ImageField(upload_to=settings.MEDIA_AVATAR_IMAGE_DIR, default='avatars/bot_avatar.jpg')

    class Meta:
        verbose_name = 'Бот'
        verbose_name_plural = 'Боты'

    def __str__(self):
        return self.name

    
class BotComment(models.Model):

    COLOR_CHOICES = (
        ('white', 'White'),
        ('red', 'Red'),
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('yellow', 'Yellow'),
        ('black', 'Black')
    )

    comment = models.TextField(verbose_name='comment')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='created date')
    color = models.CharField(max_length=6, choices=COLOR_CHOICES, verbose_name='color')
    bot = models.ForeignKey(Bot, on_delete=models.CASCADE, verbose_name='bot', related_name='comments')

    class Meta:
        verbose_name = 'Комментарии бота'
        verbose_name_plural = 'Комментарии ботов'

    def __str__(self):
        return self.comment


class Room(models.Model):

    COLORS = 'blue, white, red, black, yellow, green'
    COLOR_DESCRIPTION = 'Управление, Информация и факты, Эмоции и Чувства, Критическое суждение, Оптимистичность, Креативность'

    name = models.CharField(max_length=255, unique=True, verbose_name='name')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='created date')
    started = models.BooleanField(default=False, verbose_name='started')
    # started_time = models.DateTimeField(blank=True, null=True)
    closed = models.BooleanField(default=False, verbose_name='closed')
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, verbose_name='theme', related_name='rooms')
    users = models.ManyToManyField(User, through='RoomUser', related_name='rooms')
    bots = models.ManyToManyField(Bot, through='RoomBot', blank=True, related_name='rooms')
    colors = models.CharField(max_length=38, default=COLORS, verbose_name='colors')
    color_description = models.CharField(max_length=101, default=COLOR_DESCRIPTION, verbose_name='color_description')

    class Meta:
        verbose_name = 'Комната'
        verbose_name_plural = 'Комнаты'

    def __str__(self):
        return self.name

    def get_participants(self):
        return list(chain(self.users.order_by('roomuser__created_date'), self.bots.all()))

    def get_participants_count(self):
        return self.users.order_by('roomuser__5created_date').count() + self.bots.count()  


class RoomUser(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['room', 'user']]

    def __str__(self):
        return f'{self.room.name} - {self.user.username}'


class RoomBot(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    bot = models.ForeignKey(Bot, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['room', 'bot']]

    def __str__(self):
        return f'{self.room.name} - {self.bot.name}'


class Comment(models.Model):

    COLOR_CHOICES = (
        ('white', 'White'),
        ('red', 'Red'),
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('yellow', 'Yellow'),
        ('black', 'Black')
    )

    comment = models.TextField(verbose_name='comment')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='created date')
    color = models.CharField(max_length=6, choices=COLOR_CHOICES, verbose_name='color')
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, verbose_name='theme', related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='author', related_name='comments')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name='room', related_name='comments')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.comment
           

discussion/forms.py
from django import forms

from discussion.models import Theme


class CreateThemeForm(forms.ModelForm):
    
    class Meta:
        model = Theme
        fields = ('theme', 'problem', 'decision')

discussion/views.py
from itertools import chain

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import View, ListView, CreateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404

from discussion.models import Theme, Room, RoomUser, Comment
from accounts.models import User
from discussion.forms import CreateThemeForm


class DisplayThemesView(ListView):
    model = Theme
    context_object_name = 'themes'
    template_name = 'discussion/theme_list.html'


class CreateThemeView(CreateView):

    @method_decorator(login_required)
    def get(self, request):
        form = CreateThemeForm()
        return render(request, 'discussion/theme_create.html', {'form': form})
    
    @method_decorator(login_required)
    def post(self, request):
        form = CreateThemeForm(request.POST)

        if form.is_valid():
            theme = form.save(commit=False)
            theme.author = request.user
            theme.save()

        return redirect(reverse('main_page'))

    
class DescriptionThemeView(View):

    def get(self, request, id):

        theme = get_object_or_404(Theme, pk=id)
        return render(request, 'discussion/theme_description.html', context={'theme': theme})


class DiscussionRoomView(View):

    @method_decorator(login_required)
    def get(self, request, room_id):

        room = get_object_or_404(Room, pk=room_id)

        context = {
            'room': room,
        }

        return render(request, 'discussion/discussion.html', context)


class CreateDiscussionRoomView(View):

    @method_decorator(login_required)
    def get(self, request, theme_id):

        theme = Theme.objects.get(pk=theme_id)
        theme_current_rooms = Room.objects.filter(theme=theme)

        if theme_current_rooms.exists():
            last_current_room = theme_current_rooms.last()
            room_name = f'theme_{theme_id}_room_{last_current_room.id + 1}'
        else:
            room_name = f'theme_{theme_id}_room_1'

        room = Room.objects.create(name=room_name, theme=theme)
        RoomUser.objects.create(room=room, user=request.user)

        return redirect(reverse_lazy('discussion', kwargs={'room_id': room.pk}))

discussion/templates/discussion/chat_window.html
        <div class="col-xs-4 mt-5">

            <!-- <p class="timer">00:30:00</p> -->

            <div id="accordion"  class="accordion">
                <div class="card">
                  <a class="theme-header collapsed btn-dark" data-toggle="collapse" data-target="#collapseTheme" aria-expanded="true" aria-controls="collapseTheme">
                    {{ room.theme.theme }}
                  </a>
                  
                  <div id="collapseTheme" class="collapse" aria-labelledby="headingTheme" data-parent="#accordion">
                    <div class="card-body">
                        <strong>Проблема: </strong>
                        {{ room.theme.problem }}
                        <br>
                        <strong>Решение: </strong>
                        {{ room.theme.decision }}
                    </div>
                  </div>
                </div>
              </div>
            
            <div class="chat-card-outter card">
                <div class="chat-card card-body" id="all_messages">
                    <ul class="chat">

                        {% if request.user.is_authenticated %}
                            {% if request.user != theme.author %}
                                {% for comment in room.comments.all %}
                                    {% if comment.author == user %}
                                        <li>
                                            <div class="chat-body">
                                                <p class="text-right"><strong style="color: {{ comment.color }};">{{ comment.author }}</strong></p>
                                                <p class="text-right">{{ comment.comment }}</p>
                                            </div>
                                        </li>
                                    {% else %}
                                        <li>
                                            <div class="chat-body">
                                                <p class="text-left"><strong style="color: {{ comment.color }};">{{ comment.author }}</strong></p>
                                                <p class="text-left">{{ comment.comment }}</p>
                                            </div>
                                        </li>
                                    {% endif %}
                                {% endfor %}

                            {% else %}
                                <div>Автор темы не может участвовать в обсуждении</div>
                            {% endif %}

                        {% else %}
                            <div>Please Login</div>
                        {% endif %}
                    </ul>
                </div>
                <div class="card-footer">
                    <div class="input-group">
                        <input id="chat-message-input" type="text" class="form-control input-sm" placeholder="" />
                        <span class="input-group-btn">
                            <button class="btn btn-dark btn-md" id="chat-message-submit">Отправить</button>
                        </span>
                    </div>
                </div>
            </div>
            
            <div class="row mt-3 mb-3">
                <div class="btn btn-dark p-0 m-0 ml-4 mr-2 col-5" id="start-discussion">Начать обсуждение</div>
                <div class="btn btn-dark p-0 m-0 col-5" id="add-bots">Добавить ботов</div>
            </div>
            <div class="row mt-3 mb-3">
                <div class="btn btn-dark p-0 m-0 ml-4 mr-2 col-5" id="leave-room">Покинуть комнату</div>
                <div class="btn btn-dark p-0 m-0 col-5" id="delete-bots">Удалить бота</div>
            </div>            
        </div>

discussion/templates/discussion/color_discription.html
<div class="colors-descriotion mt-3 ml-4">
    <button class="btn btn-dark" type="button" data-toggle="collapse" data-target="#collapseDescription" aria-expanded="false" aria-controls="collapseDescription">
        Подробное описание значение цвета шляп
    </button>
    <div id="collapseDescription" class="collapse" aria-labelledby="headingTheme" data-parent="#accordion">
        <div class="card-body">
            <strong>Белая шляпа: информация</strong>
            <span>Белая шляпа используется для того, чтобы направить внимание на информацию. 
                В этом режиме мышления нас интересуют только факты. Мы задаемся вопросами о том, 
                что мы уже знаем, какая еще информация нам необходима и как нам ее получить.</span>
            <br>
            <strong>Красная шляпа: чувства и интуиция</strong>
            <span>В режиме красной шляпы у участников сессии появляется возможность высказать свои 
                чувства и интуитивные догадки относительно рассматриваемого вопроса, не вдаваясь в 
                объяснения о том, почему это так, кто виноват и что делать.</span>
            <br>
            <strong>Черная шляпа: критика</strong>
            <span>Черная шляпа позволяет дать волю критическим оценками, опасениям и осторожности. 
                Она защищает нас от безрассудных и непродуманных действий, указывает на возможные риски 
                и подводные камни. Польза от такого мышления несомненна, если, конечно, им не злоупотреблять.</span>
            <br>
            <strong>Желтая шляпа: логический позитив</strong>
            <span>Желтая шляпа требует от нас переключить свое внимание на поиск достоинств, преимуществ 
                и позитивных сторон рассматриваемой идеи.</span>
            <br>
            <strong>Зеленая шляпа: креативность</strong>
            <span>Находясь под зеленой шляпой, мы придумываем новые идеи, модифицируем уже существующие, 
                ищем альтернативы, исследуем возможности, в общем, даем креативности зеленый свет.</span>
            <br>
            <strong>Синяя шляпа: управление процессом</strong>
            <span>Синяя шляпа отличается от других шляп тем, что она предназначена не для работы с 
                содержанием задачи, а для управления самим процессом работы. В частности, 
                ее используют в начале сессии для определения того, что предстоит сделать, и в конце, 
                чтобы обобщить достигнутое и обозначить новые цели.</span>
        </div>
    </div>
</div>

discussion/templates/discussion/discussion.html
{% extends 'base.html' %}

{% block content %}

    {% if room.closed %} 
        <div class="info-about-room">
            <p>Данное обсуждение завершено, присоединитесь к другому или создайте свое</p>
        </div>
    {% else %}
        {% include 'discussion/discussion_room.html' %}
    {% endif %}

{% endblock %}

discussion/templates/discussion/discussion_room.html
{% load staticfiles %}

<div class="container">
    {% include 'discussion/popup_window.html' %}

    <div class="row" style="flex-wrap: wrap;">
        <div class="col-7">
            
            {% include 'discussion/color_discription.html' %}

            <div class="row room-users">
                <img src ="{% static 'image/table.png' %}">
                {% include 'discussion/users_avatars.html' %}
            </div>
        </div>
        {% include 'discussion/chat_window.html' %}
    </div>
</div>

{{ room.pk|json_script:"room_id" }}
{{ room.started|json_script:"room_is_started" }}
<script>
    
    $('#all_messages').scrollTop($('#all_messages')[0].scrollHeight);
    const roomID = JSON.parse(document.getElementById('room_id').textContent);
    const roomIsStarted = JSON.parse(document.getElementById('room_is_started').textContent);
    const wsScheme = window.location.protocol == "https:" ? "wss" : "ws";
    const discussionSocket = new WebSocket(wsScheme + '://' + window.location.host + '/ws/discussion/' + roomID + '/');
    
    const maxNumberParticipants = 6;
    const discussionTimeOneUser = 300000;
    let botCommentGetTimeIntervalId;

    discussionSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const message = data['message'];
        const receiveUser = data['user'];
        const user = '{{ user }}';
        let colors = data['colors']
        let colorDescription = data['color_description']
        const botName = data['bot_name'];
        const botComment = data['bot_comment'];

        if (!!message && !!receiveUser) {
            if (receiveUser === user) {
                let color = getColor(receiveUser);
                $('<li><div class="chat-body"><p class="text-right"><strong style="color:' + color + ';">' + 
                    receiveUser + '</strong></p><p class="text-right">' + message + 
                        '</p></div></li>').appendTo($('.chat'))
            } else {
                $('<li><div class="chat-body"><p class="text-left"><strong style="color:' + color + ';">' + 
                    receiveUser + '</strong></p><p class="text-left">' + message + 
                        '</p></div></li>').appendTo($('.chat'))
            };
        }
        
        // $('#all_messages').scrollTop($('#all_messages')[0].scrollHeight);
  
        if (data['room_users']) {
            const newRoomUsers = JSON.parse(data['room_users'])
            const roomBots = JSON.parse(data['bots'])

            let roomParticipantsHtml = ''
            for (let i in newRoomUsers) {
                roomParticipantsHtml = roomParticipantsHtml + 
                '<div class="user-avatar avatar-' + (parseInt(i) + 1) + ' col-3 m-1" title=""> \
                    <img class="card-img-top" src="/media/' + newRoomUsers[i].fields.avatar + '" alt="User avatar"> \
                    <h6 align="center" class="user-name">' + newRoomUsers[i].fields.username + '</h6> \
                </div>';
            }
            
            if (roomBots) {
                if (roomBots.length === 1 && roomBots[0].fields.name === 'bot_1') {
                    roomParticipantsHtml = roomParticipantsHtml +
                    '<div class="user-avatar avatar-' + 6 + ' col-3 m-1" title="" > \
                        <img class="card-img-top" src="/media/' + roomBots[0].fields.avatar + '" alt="User avatar"> \
                        <h6 align="center" class="user-name">' + roomBots[0].fields.name + '</h6> \
                    </div>';
                } else {
                    for (let i in roomBots) {
                        roomParticipantsHtml = roomParticipantsHtml +
                        '<div class="user-avatar avatar-' + (parseInt(i) + 5) + ' col-3 m-1" title="" > \
                            <img class="card-img-top" src="/media/' + roomBots[i].fields.avatar + '" alt="User avatar"> \
                            <h6 align="center" class="user-name">' + roomBots[i].fields.name + '</h6> \
                        </div>';
                    }   
                }
            }  

            $('.user-avatars').html($(roomParticipantsHtml)); 
            $('.user-avatar').tooltip();  
        }

        if (colors) {
            colors = JSON.parse(colors);
            colorDescription = JSON.parse(colorDescription);
            console.log(colors);
            // startTimer();
            changeColor(colors, colorDescription);
            getBotComment();
        }      

        if (data['bot_name']) {

            let color = getColor(botName);
            
            $('<li><div class="chat-body"><p class="text-left"><strong style="color:' + color + ';">' + 
                botName + '</strong></p><p class="text-left">' + botComment + 
                    '</p></div></li>').appendTo($('.chat'))
            
                $('#all_messages').scrollTop($('#all_messages')[0].scrollHeight);
        }
    }


    discussionSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
        console.error(e)
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) {
            document.querySelector('#chat-message-submit').click();
        }
    };

    const getColor = (name) => {
        let roomParticipants = document.querySelectorAll(".room-users .user-avatar");
        for (participant of roomParticipants) {
            if (name === participant.innerText && participant.style.borderColor) {
                let color = participant.style.borderColor;
                return color;
            }
        }
    }

    document.querySelector('#chat-message-submit').onclick = function (e) {
        const messageInput = document.querySelector('#chat-message-input');
        const message = messageInput.value;

        let colorValue;
        let roomParticipants = document.querySelectorAll(".room-users .user-avatar");
        let colorsList = ['blue', 'white', 'red', 'black', 'yellow', 'green'];
        
        for (let i = 0; i < roomParticipants.length; i++) {
            if ('{{ user }}' === roomParticipants[i].innerText) {
                if (colorsList.indexOf(roomParticipants[i].style.borderColor) !== -1) {
                    colorValue = roomParticipants[i].style.borderColor;
                }
            }
        }

        discussionSocket.send(JSON.stringify({
            'message': message,
            'colorValue': colorValue,
        }));

        messageInput.value = '';
    };

    document.querySelector("#leave-room").onclick = function(e) {

        let roomParticipants = document.querySelectorAll(".room-users .user-avatar");
        let colorsList = ['blue', 'white', 'red', 'black', 'yellow', 'green'];

        if (roomIsStarted === false && colorsList.indexOf(roomParticipants[0].style.borderColor) === -1) {
                discussionSocket.send(JSON.stringify({
                'isUserLeaveRoom': true,
            }));

            window.location.replace(`${window.location.protocol}//${window.location.host}`);
        } else {
            alert('Вы не можете покинуть комнату, т.к. обсуждение начато!');
        }    
    }

    document.querySelector("#start-discussion").onclick = function(e) {
        let roomParticipants = document.querySelectorAll(".room-users .user-avatar");
        let colorsList = ['blue', 'white', 'red', 'black', 'yellow', 'green'];

        if (colorsList.indexOf(roomParticipants[0].style.borderColor) === -1) {
            if (roomIsStarted === false) {
                if (roomParticipants.length === maxNumberParticipants) {
                discussionSocket.send(JSON.stringify({
                    'isDiscussionStart': true,
                }));
            } else {
                    alert('Недостаточно участников!');
                }
            } else {
                alert('Обсуждение начато!');
            }   
        } else {
                alert('Обсуждение начато!');
            } 
    }

    document.querySelector("#add-bots").onclick = function(e) {
        let roomParticipants = document.querySelectorAll(".room-users .user-avatar");

        if (roomParticipants.length >= 4 && roomParticipants.length < 6) {
            discussionSocket.send(JSON.stringify({
                'isBotsAdd': true,
            }));
        } else {
            alert('Для добавления ботов участников должно быть >= 4 и < 6.');
        }
    }

    document.querySelector("#delete-bots").onclick = function(e) {
        let roomParticipants = document.querySelectorAll(".room-users .user-avatar");

        if (roomIsStarted === false) {

            if ((roomParticipants[4].innerText === 'bot_1' && roomParticipants[5].innerText === 'bot_2') 
                || (roomParticipants[4].innerText === 'bot_2') || (roomParticipants[5].innerText === 'bot_1')) {
                discussionSocket.send(JSON.stringify({
                    'isDeleteBot': true
                }));
            } else {
                alert('В комнате нет ботов.');
            }
        } else {
            alert('Обсуждение начато, невозможно удалить бота.');
        }
    }


    function changeColor(colors, colorDescription) {
        let roomParticipants = document.querySelectorAll(".room-users .user-avatar");
        let namesInChatWindow = document.querySelectorAll("#all_messages .chat li")

        if (roomParticipants[0].style.border !== `10px solid ${colors[0]}`) {
            if (colors[0] === 'blue') {
                document.querySelector('.popup-window .popup-content .popup-body p').innerText = 'Начало обсуждения'
            } else {
                document.querySelector('.popup-window .popup-content .popup-body p').innerText = 'Получение цвета'
            }
            $('.popup-window').fadeIn(1200);
            $('.popup-window').fadeOut(1200);
        }
       
        for (let i = 0; i < maxNumberParticipants; i++) {
            roomParticipants[i].style.border = `10px solid ${colors[i]}`;
            roomParticipants[i].style.background = colors[i];
            roomParticipants[i].setAttribute('data-original-title', colorDescription[i]);
        }

        // for (let item of namesInChatWindow) {
        //     let name = item.querySelector('p').innerText;
        //     for (let j in roomParticipants) {
        //         if (name === roomParticipants[j].innerText) {
        //             item.querySelector('p strong').style.color = roomParticipants[j].style.background;
        //         }
        //     }
        // }

        if (roomParticipants.length < maxNumberParticipants) {
            clearInterval(botCommentGetTimeIntervalId);

            for (let i = 0; i < roomParticipants.length; i++) {
                roomParticipants[i].style.border = '10px solid #343a40';
                roomParticipants[i].style.background = '#343a40';
            }
        }

        if (colors[5] === 'blue') {
            clearInterval(botCommentGetTimeIntervalId);
            setTimeout(() => {
                discussionSocket.send(JSON.stringify({
                    'closed': true
                }));

                for (let i = 0; i < roomParticipants.length; i++) {
                    roomParticipants[i].style.border = '10px solid #343a40';
                    roomParticipants[i].style.background = '#343a40';
                }
                discussionSocket.onclose();
                alert('Обсуждение завершено!');
                window.location.replace(`${window.location.protocol}//${window.location.host}`);
            }, discussionTimeOneUser + 15000);
        }
    };


    function getBotComment(bot) {
        let botName;
        let timeGetBotComment = Math.floor(Math.random() * (180000 - 60000)) + 60000; // 1-3 мин.
        
        botCommentGetTimeIntervalId = setInterval(() => {

            let roomParticipants = document.querySelectorAll(".room-users .user-avatar");
            timeGetBotComment = Math.floor(Math.random() * (180000 - 60000)) + 60000;

            if (bot === 'bot_1' || bot === 'bot_2') {
                botName = bot;
            } else {
                botName = `bot_${Math.floor(Math.random() * (3 - 1)) + 1}`
            }
            let botIndex;
            for (let i = 0; i < roomParticipants.length; i++) {
                if (roomParticipants[i].innerText === botName) {
                    botIndex = i;
                }
            }

            try {
                discussionSocket.send(JSON.stringify({
                    'isGetBotComment': true,
                    'botName': botName,
                    'botColor': roomParticipants[botIndex].style.borderColor
                }));

            } catch (error) {
                console.log('get bot comment error', error);
            }
        }, timeGetBotComment);
    }


    // let duration_timer = 360; //1800// 30 minutes
    // let timerElement = document.querySelector('.timer')

    // function startTimer() {
      
    //     let timer = duration_timer, minutes, seconds;
        
    //     timerIntervalId = setInterval(function() {
    //         minutes = parseInt(timer / 60, 10)
    //         seconds = parseInt(timer % 60, 10);

    //         minutes = minutes < 10 ? "0" + minutes : minutes;
    //         seconds = seconds < 10 ? "0" + seconds : seconds;

    //         timerElement.textContent = `00:${minutes}:${seconds}`;
    //         if (--timer < 0) {
    //             clearInterval(timerIntervalId);
    //         }

    //     }, 1000);
    // };

</script>

discussion/templates/discussion/popup_window.html
<div class="popup-window">
    <div class="popup-content">
      <div class="popup-body">
        <p>Смена цвета</p>
      </div>
    </div>
</div>

discussion/templates/discussion/theme_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <p class="h2 mt-3 mb-5 font-weight-light text-center">Добавить новую тему для обсуждения</p>
    <form class="mb-3" method="post">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control mb-3" placeholder="Тема" type="text" name="theme" maxlength="255" required="" id="id_theme">
            <textarea class="form-control" placeholder="Проблема" name="problem" cols="40" rows="10" required="" id="id_problem"></textarea>
            <textarea class="form-control" placeholder="Решение" name="decision" cols="40" rows="10" required="" id="id_decision"></textarea>
        </div>
        <button class="btn btn-primary btn-lg btn-block " type="submit">Добавить тему</button>
    </form>
</div>

{% endblock %}

discussion/templates/discussion/theme_description.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <div class="mt-5">
          <h3>{{ theme.theme }}</h3>
          <p class="mb-2 text-muted">{{ theme.author }}</p>
          <p class="mb-2 text-muted">{{ theme.created_date }}</p>
          <p class="card-text"><strong>Проблема: </strong>{{ theme.problem }}</p>
          <p class="card-text"><strong>Решение: </strong>{{ theme.decision }}</p>
      </div>
</div>

{% endblock %}

discussion/templates/discussion/topic_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <p class="h2 mt-3 mb-5 font-weight-light text-center">Добавить новую тему для обсуждения</p>
    <form class="mb-3" method="post">
        {% csrf_token %}

        <div class="form-group">
            <textarea class="form-control" name="topic" cols="40" rows="10" required="" id="id_topic"></textarea>
        </div>
        <button class="btn btn-primary btn-lg btn-block " type="submit">Добавить тему</button>
    </form>
</div>

{% endblock %}